param(
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\ui\src\domain\history.ts')
)

$ErrorActionPreference = 'Stop'
$officialHeaders = @{
    'User-Agent' = 'Mozilla/5.0'
    'Referer' = 'https://www.cwl.gov.cn/ygkj/wqkjgg/ssq/'
}
$historyHeaders = @{
    'User-Agent' = 'Mozilla/5.0'
    'Referer' = 'https://datachart.500.com/ssq/history/history.shtml'
}

function Get-OfficialPage([int]$PageNo) {
    $uri = 'https://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice' +
        "?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=2003-01-01" +
        "&dayEnd=$((Get-Date).ToString('yyyy-MM-dd'))&pageNo=$PageNo&pageSize=30&week=&systemType=PC"
    $response = Invoke-WebRequest -Uri $uri -Headers $officialHeaders -UseBasicParsing
    $data = $response.Content | ConvertFrom-Json
    if ($data.state -ne 0) {
        throw "中国福彩网第 $PageNo 页查询失败：$($data.message)"
    }
    return $data
}

$firstOfficialPage = Get-OfficialPage 1
$latestOfficialIssue = [string]$firstOfficialPage.result[0].code
if ($latestOfficialIssue -notmatch '^20\d{5}$') {
    throw "无法识别最新期号：$latestOfficialIssue"
}

$official = @{}
for ($page = 1; $page -le [int]$firstOfficialPage.pageNum; $page++) {
    $data = if ($page -eq 1) { $firstOfficialPage } else { Get-OfficialPage $page }
    foreach ($draw in $data.result) {
        $date = ([string]$draw.date).Substring(0, 10)
        $official[[string]$draw.code] = "$($draw.red)|$($draw.blue)|$date"
    }
}

$latestShortIssue = $latestOfficialIssue.Substring(2)
$historyUrl = 'https://datachart.500.com/ssq/history/newinc/history.php' +
    "?start=03001&end=$latestShortIssue"
$historyHtml = (Invoke-WebRequest -Uri $historyUrl -Headers $historyHeaders -UseBasicParsing).Content
$rows = [regex]::Matches($historyHtml, '(?is)<tr[^>]*class="t_tr1"[^>]*>(.*?)</tr>')
if ($rows.Count -lt 3000) {
    throw "历史数据数量异常，只解析到 $($rows.Count) 期"
}

$draws = foreach ($row in $rows) {
    $cells = @(
        [regex]::Matches($row.Groups[1].Value, '(?is)<td[^>]*>(.*?)</td>') |
            ForEach-Object {
                [System.Net.WebUtility]::HtmlDecode(
                    [regex]::Replace($_.Groups[1].Value, '<[^>]+>', '')
                ).Trim()
            }
    )
    if ($cells.Count -lt 17) {
        throw '历史数据行字段不足'
    }
    $issue = '20' + $cells[1]
    $reds = @($cells[2..7] | ForEach-Object { [int]$_ })
    $blue = [int]$cells[8]
    $date = $cells[16]
    if ($issue -notmatch '^20\d{5}$' -or
        $date -notmatch '^\d{4}-\d{2}-\d{2}$' -or
        $reds.Count -ne 6 -or
        (@($reds | Select-Object -Unique)).Count -ne 6 -or
        @($reds | Where-Object { $_ -lt 1 -or $_ -gt 33 }).Count -gt 0 -or
        $blue -lt 1 -or $blue -gt 16) {
        throw "第 $issue 期数据校验失败"
    }
    [pscustomobject]@{
        Issue = $issue
        Date = $date
        Reds = $reds
        Blue = $blue
    }
}

$draws = @($draws | Sort-Object Issue -Descending)
$duplicates = @($draws | Group-Object Issue | Where-Object Count -gt 1)
if ($duplicates.Count -gt 0) {
    throw "存在重复期号：$($duplicates.Name -join ', ')"
}
if ($draws[0].Issue -ne $latestOfficialIssue -or $draws[-1].Issue -ne '2003001') {
    throw "历史区间异常：$($draws[0].Issue) - $($draws[-1].Issue)"
}

$historyByIssue = @{}
foreach ($draw in $draws) {
    $redText = ($draw.Reds | ForEach-Object { $_.ToString('00') }) -join ','
    $historyByIssue[$draw.Issue] = "$redText|$($draw.Blue.ToString('00'))|$($draw.Date)"
}
$mismatches = foreach ($issue in $official.Keys) {
    if ($official[$issue] -ne $historyByIssue[$issue]) {
        $issue
    }
}
if (@($mismatches).Count -gt 0) {
    throw "与中国福彩网数据不一致：$(@($mismatches)[0..([Math]::Min(9, @($mismatches).Count - 1))] -join ', ')"
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("import type { Draw } from './types'")
[void]$builder.AppendLine()
[void]$builder.AppendLine("// Generated by scripts/sync-ssq-history.ps1 on $((Get-Date).ToString('yyyy-MM-dd')).")
[void]$builder.AppendLine("// $($draws.Count) draws: $($draws[-1].Issue) through $($draws[0].Issue).")
[void]$builder.AppendLine('// 2013+ records are cross-checked against the China Welfare Lottery official API.')
[void]$builder.AppendLine('const RAW_DRAWS = `')
foreach ($draw in $draws) {
    $numbers = @($draw.Reds) + $draw.Blue
    [void]$builder.AppendLine("$($draw.Issue),$($draw.Date),$(($numbers | ForEach-Object { $_.ToString('00') }) -join ',')")
}
[void]$builder.AppendLine('`')
[void]$builder.AppendLine()
[void]$builder.AppendLine(@'
export const BUILTIN_DRAWS: Draw[] = RAW_DRAWS.trim()
  .split('\n')
  .map((line) => {
    const [issue, date, ...numbers] = line.split(',')
    return {
      issue: issue!,
      date: date!,
      reds: numbers.slice(0, 6).map(Number),
      blue: Number(numbers[6]),
    }
  })
'@)

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.File]::WriteAllText(
    $resolvedOutput,
    $builder.ToString(),
    [System.Text.UTF8Encoding]::new($false)
)
Write-Host "Wrote $($draws.Count) draws to $resolvedOutput; official overlap verified: $($official.Count)."
